services:
  - type: web
    name: bot-manager-telegram
    runtime: python
    pythonVersion: 3.10.13
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false
